#server:
#  port: 9091

spring:
  application:
    name: scaf-service
  datasource:
    url: jdbc:mysql://localhost:3306/sistema_scaf
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    restart:
      enabled: true